### ISSUE TITLE
Updating the Appointment comment with Video link

### ISSUE THREAD

**Issue by brianpos** [grahamegrieve/ClinicArrivals#3]
When updating the notes with the video link, check that it's not already there. and potentially replace the reference, or at least do something...

**Comment by brianpos** [comment]
I put in a simple check to see if the comment already contains the exact text don't update, would this be good enough?

**Comment by grahamegrieve** [comment]
I'm not sure I follow this. We don't have a way to not mark it as a video, so I'm not sure we should invest in removing existing text - just keep appending

**Comment by brianpos** [comment]
So what we have is good enough then. If the exact text we're trying to append is there, then don't otherwise add it
Close issue if you think this is good enough.

**Comment by grahamegrieve** [comment]
yes this is ok - superceded by other approache
